# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.11.0
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: false
github_check_license: false
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 16.0
org_name: Noviat
org_slug: Noviat
rebel_module_groups: []
repo_description: 'Noviat Generic - Accounting Repository'
repo_name: accounting
repo_slug: accounting
repo_website: https://picasso.noviat.com/Noviat/Noviat_Generic/accounting/
travis_apt_packages: []
travis_apt_sources: []

